### ISSUE TITLE
flashSettingsWithTimeout does not override default 10 second timeout

### ISSUE THREAD

**Issue by ronaldho** [novaphotos/nova-ios-sdk#13]
Hi there,

I'm not sure if I'm doing something wrong, but I've looked through the documentation and also tried it with the provided code snippet 
`let settings = NVFlashSettings.warm().flashSettingsWithTimeout(20000) // in milliseconds`
for flashSettingsWithTimeout, and it does not seem to override the default 10 second timeout in the SDK. Here is the code I'm working with:

```
    var warm:UInt8 = 255;
    var cool:UInt8 = 125
   @IBAction func flashOn(sender:UIButton){
        let flashSettings = NVFlashSettings.customWarm(warm, cool: cool).flashSettingsWithTimeout(30000)
        for flash in appDelegate.flashService.connectedFlashes as! [NVFlash] {
            // toggle flash
            if (!flash.lit) {
                flash.beginFlash(flashSettings)
            } else {
                flash.endFlash()
            }
        }

    }
```

Any help is much appreciated!

**Comment by joewalnes** [comment]
The hardware will automatically shut the light off after a 10 second timeout. This is a safety mechanism in case there phone or Bluetooth stack ever gets in a hung state.

To flash longer than 10 seconds you'll have to periodically reset the timeout by calling beginFlash again. This will keep it lit continuously the most recent beginFlash times out, or a subsequent endFlash.

If your intent is a 20 second flash - this would be fine. However at approximately a minute the hardware starts getting hot and can behave unpredictably as it's only designed for short bursts. Also long flashes drain the battery really quickly.

**Comment by ronaldho** [comment]
thanks! this has been informative!
